name: Deploy
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub Actions
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/ekatrinaak/films-backend:latest
